include $(TOPDIR)/rules.mk

PKG_NAME:=luci-app-homebox
PKG_VERSION:=1.0.1
PKG_RELEASE:=1
PKG_MAINTAINER:=sirpdboy

LUCI_TITLE:=LuCI support for Homebox Speed Test
LUCI_DEPENDS:=+homebox
LUCI_PKGARCH:=all

include $(TOPDIR)/feeds/luci/luci.mk

# call BuildPackage - OpenWrt buildroot signature