#!/bin/sh /etc/rc.common

USE_PROCD=1
START=99

CONF="homebox"
PROG="/usr/bin/homebox"

start_service() {
	config_load "$CONF"
	local enabled port
	config_get_bool enabled "main" "enabled" 0
	config_get port "main" "port" "3300"

	[ "$enabled" -eq 1 ] || return 1

	procd_open_instance
	# 执行命令: /usr/bin/homebox serve --port [端口]
	procd_set_param command "$PROG" serve --port "$port"
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_set_param respawn
	procd_close_instance
}

service_triggers() {
	procd_add_reload_trigger "homebox"
}